from .user import User
from .student import Student
from .message import Conversation
from .university import University
from .instructor import Instructor
from .batch import Batch
from .assignment import Assignment
from .submission import Submission
from .admin import Admin